include ../utils/Makefrag

SOURCE_URL = $(GNU_MIRROR)/gnu/less/less-679.tar.gz
SOURCE_FILE = less-679.tar.gz
SOURCE_DIR = less-679
CONFIG_ARGS = --prefix=$(PREFIX) --disable-static --enable-shared --host $(OHOS_ARCH)-unknown-linux-musl

$(eval $(call define_autotools_package))
